#!/bin/python
# -*- coding: utf-8 -*-

def read_esp_pyresp(filename):
	"""
		load the esp data generated by PyRESP or pol_resp
	"""
	esp_qm = []
	esp_cal = []
	with open(filename,'r') as f:
		while True:
			line = f.readline()
			if not line:
				break
			else:
				if 'nesp' in line:
					nesp = int(line.split()[1])
					natom = int(line.split()[3])
					# skip line "X Y Z esp_qm esp_clc diff"
					line = f.readline()
					for i in range(nesp):
						line = f.readline()
						esp_qm.append(float(line.split()[3]))
						esp_cal.append(float(line.split()[4]))

	return esp_qm,esp_cal
					
def ESPDIFF(esp_cal,esp_qm):
	sd = 0
	ssd = 0
	r1 = 0
	r2 = 0
	s1 = 0
	s2 = 0
	
	nqm = len(esp_qm)
	ncal = len(esp_cal)

	if nqm != ncal:
		diff = 'no match'
	else:
		for i in range(nqm):
			sd +=esp_cal[i] - esp_qm[i]
			ssd +=(esp_cal[i] - esp_qm[i])**2
			r1 +=esp_cal[i]**2
			r2 +=esp_qm[i]**2
			s1 +=esp_cal[i]
			s2 +=esp_qm[i]

		sd = sd/nqm
		ssd = ssd/nqm
		r1 = r1/ncal
		r2 = r2/nqm
		s1 = s1/ncal
		s2 = s2/nqm

		ssd -=sd*sd
		r1  -=s1*s1
		r2  -=s2*s2

		diff = ssd**0.5/(0.5*(r1+r2))**0.5

	return diff

def ESP_rmsd(esp_cal, esp_qm):
	"""
	esp_cal: queried one
	esp_qm: referenced one
	"""
	ssd =0
	r1=0
	r2=0
	nqm = len(esp_qm)
	ncal = len(esp_cal)

	if nqm == ncal:
		for i in range(nqm):
			ssd+=(esp_cal[i]-esp_qm[i])**2
			r1 +=esp_cal[i]**2
			r2 +=esp_qm[i]**2

		ssd = ssd/nqm
		r1 = r1/nqm
		r2 = r2/ncal

		rms  = ssd**0.5
		rrms = rms/r2**0.5

	return rms, rrms


if __name__ == '__main__':
	pass
